run:
  timeout: 5m
  tests: true
  skip-dirs:
    - examples

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gocritic
    - gosimple
    - unused

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/costco-go
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
    - path: cmd/
      linters:
        - errcheck